### ISSUE TITLE
Incremental mode

### ISSUE THREAD

**Issue by pkolaczk** [pkolaczk/fclones#11]
Persist hashes to a file in order to speedup subsequent runs or to avoid recomputing hashes when the previous run was interrupted.

**Comment by yehia2amer** [comment]
> Do you mean saving metadata of intermediate stages to avoid hashing again? It would be definitely possible, but this one is a bit more work than the other ideas.

Yes I mean that the tool creates a simple file/datastore like:
| ID | Path | Size  | Modify_TimeStamp | initialHash | initialHash | EndFileHash | EndFileHash | FullHash | FclonesStatus
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |

That way If the Tool Stopped, Power is lost, or even I Rerun the tool again after a couple of weeks. It won't recalculate Hashes if Path, Size, and Modified Date are the same !

of course I am just brainstorming here, and I also know that it would affect performance a little bit as we are writing to disk instead of using hash-maps. but at the same time it would dramatically reduce time starting from the second run !

**Comment by pkolaczk** [comment]
Makes sense.

**Comment by Architector4** [comment]
I second this. I want to run a large dedup operation on a lot of snapshots, but the best time I can dedicate is a night, which isn't enough to find all duplicate files. It would be nice to somehow be able to interrupt the program and let it write current partial results in a file (exact progress or at least up until the ongoing stage), and then on a later date run fclones again, continuing the progress.

The actions are already split into two separate subsequent runs of the program - a "find all duplicates" and a "do something with them" runs. I feel like it makes sense to allow breaking the first one up into its own stages with an intermediate file aswell.

**Comment by EthanHindmarsh** [comment]
> Yes I mean that the tool creates a simple file/datastore like:

Could Path not act as ID? Not sure what having an ID would be useful for
Only issue I could see with this is if a user had two files with identical mtimes, deleted the first, and renamed the second file to the first - Identical mtimes, but ctime would change
Also, would this file / datastore ever be cleaned?

**Comment by pkolaczk** [comment]
#111
