### ISSUE TITLE
23000 symlinks created...?

### ISSUE THREAD

**Issue by KyleSanderson** [pkolaczk/fclones#196]
0.30.0

```
fclones group --cache /mnt/*T* > dupes.txt
fclones link < dupes.txt
```

Looks like it riddled all my disks with symlinks, preventing my containers from accessing the associated data... there's a switch for symlinks and I didn't use that. Is there a way to undo this to recover my damaged data (and prevent it from happening in the future).

**Comment by th1000s** [comment]
I also think that the automatic fallback to symbolic links is unexpected and therefore bad behavior. Per default fclones should not do any cross-device actions, because in this case it means deleting data!

To undo that you have to write a script to track down and fix these symlinks yourself, sorry.
