### ISSUE TITLE
Dedup on btrfs (and others)

### ISSUE THREAD

**Issue by ChrisJefferson** [pkolaczk/fclones#54]
Btrfs supports in place dedup ( https://btrfs.wiki.kernel.org/index.php/Deduplication ), via a syscall. This is completely safe, as checks if the files are identical before deduping.

This would be very Linux specific low level code.

**Comment by pkolaczk** [comment]
Thanks, this is a great idea!

**Comment by ilyapopov** [comment]
See also [FICLONE ioctl](https://man7.org/linux/man-pages/man2/ioctl_ficlonerange.2.html) which is supported by a few CoW filesystems (Btrfs, XFS, and also NFS and SMB for server-side clones) Exists since Linux 4.5.

There is also [copy_file_range](https://man7.org/linux/man-pages/man2/copy_file_range.2.html) syscall.

**Comment by th1000s** [comment]
See #74, I'd appreciate some design feedback.

**Comment by patrickwolf** [comment]
> See also [FICLONE ioctl](https://man7.org/linux/man-pages/man2/ioctl_ficlonerange.2.html) which is supported by a few CoW filesystems (Btrfs, XFS, and also NFS and SMB for server-side clones) Exists since Linux 4.5.

I noticed that FICLONE is unfortunately only for cloning and not for deduplication as it DOES NOT CHECK CONTENT. 
Created a ticket here to suggest switching to FIDEDUPERANGE #293
